#!/bin/sh
set -e
#
#-- Version Date: 10-02-2026 -- (dd-mm-eeyy)
#
python3 tools/git-hooks/lastChanged.py
python3 tools/git-hooks/bumpProgVersion.py

# Add only staged files (added/copied/modified)
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(c|cpp|h)$' || true)

if [ -n "$FILES" ]; then
  echo "$FILES" | xargs clang-format -i
  echo "$FILES" | xargs git add
fi
